### ISSUE TITLE
Merge contributions from fork tofi86/Jarbundler

### ISSUE THREAD

**Issue by tofi86** [UltraMixer/JarBundler#1]
Hi,

I'm one of the recent contributors to informagen's JarBundler and I've added some improvements in the past year which didn't make it in the official release.
That's why they live in a separate repo here on GitHub: https://github.com/tofi86/Jarbundler/

It would be nice if you could merge these changes to your official repo now that you've taken over the ownership of JarBundler!

Modifications (also see my Readme):
- **version 2.5.0** (2015-11-06)
  - Added optional `contentSize` attribute to JarBundler task (for Plist key `NSPreferencesContentSize`)
- **version 2.4.0** (2015-05-15)
  - Added optional `useJavaXKey` attribute to JarBundler task (for [universalJavaApplicationStub](https://github.com/tofi86/universalJavaApplicationStub)-Support)
  - Added optional `hiResCapable` attribute to JarBundler task (for Plist key `NSHighResolutionCapable`)
  - removed deprecated `aboutmenuname` attribute
  - removed deprecated `infostring` and `shortinfostring` attributes (use `copyright` attribute instead)
- **version 2.3.0** (2014-04-01)
  - Added optional `copyright` attribute to JarBundler task (for Plist key `NSHumanReadableCopyright`)
  - Issue a warning when using deprecated `aboutmenuname` attribute
  - Issue a warning when using deprecated `shortinfostring` attribute
- **version 2.2.1** (2014-01-25)
  - Added optional `allowMixedLocalizations` attribute to ant task. If `true`, the bundle supports the retrieval of localized strings from frameworks. This should be set to true if your app supports different languages. Default: `false`

**Comment by tobium** [comment]
Hi, thanks! I will merge your changes within the next days.

**Comment by tofi86** [comment]
Great! :+1: 
Looking forward to it :-)

**Comment by tofi86** [comment]
@tobium what's the status of this? Would it help if I sent a PullRequest?
But this doesn't seem so easy as you discarded the project's SVN history and did a code refactoring...

**Comment by tobium** [comment]
I just merged your changes and added you as contributor. Thanks for your recent contributions.

**Comment by tofi86** [comment]
Awesome! :+1: Thanks!
Will do a review soon...

And thanks for adding me as a collaborator & committer to this project!
