### ISSUE TITLE
Getting the following after creating a .app although I have java 1.8x installed

### ISSUE THREAD

**Issue by dhowe** [UltraMixer/JarBundler#10]
![screen shot 2016-11-27 at 5 19 04 am](https://cloud.githubusercontent.com/assets/737638/20643941/0b6afb54-b461-11e6-943b-80191d15d95f.png)

```
<project name="Pataclysm" default="export" basedir=".">
	<target name="export">
		
		<jar destfile="tmp/app.jar" basedir="bin"/>
		
		<jarbundler dir="/Users/dhowe/Desktop/" name="Pataclysm" jvmversion="1.8" mainclass="core.Pataclysm">
			<jarfileset dir="lib">
				<include name="**/*.jar" />
			</jarfileset>
			<jarfileset dir="tmp">
				<include name="**/*.jar" />
			</jarfileset>
		</jarbundler>	
	</target>
</project>
```
![screen shot 2016-11-27 at 5 20 58 am](https://cloud.githubusercontent.com/assets/737638/20643952/4e8b27c4-b461-11e6-8e57-d53972fb30f9.png)

**Comment by tofi86** [comment]
That has nothing to do with the `JarBundler` project. 

You have the JRE browser plugin installed which does not register as Java VM on the system so apps can use it.
If you want a JVM for App usage, you have to install the JDK.

OR you can use an alternative JavaApplicationStub like mine: https://github.com/tofi86/universalJavaApplicationStub
It will also try to use the JRE browser plugin when possible...
