### ISSUE TITLE
Wrong link to docs/index.html

### ISSUE THREAD

**Issue by peterdell** [UltraMixer/JarBundler#13]
The link on the main page:

"Take a look at ./docs/index.html (Currently outdated. Sorry.)"

points to a non-existing site instead of the ./docs/index.html from the current HEAD revision.

Regards, Peter.

**Comment by slajar** [comment]
please provide a PR here. Thanks

**Comment by tofi86** [comment]
Solved. Thanks for the hint @peterdell

**Comment by peterdell** [comment]
Thanks!
