### ISSUE TITLE
some bug fixes?

### ISSUE THREAD

**Issue by RBornat** [UltraMixer/JarBundler#16]
I've been working on a cloned version of jarbundler-3.3.0. I had thought of publishing it myself, but are you interested in a pull request? Small things so far (getting rid of deprecation warnings; JVMVersion also in Oracle plist; parsing modern version numbers (e.g. "9+") in setJVMVersion). 

If you are interested, I'll send a pull request. If not, I'll keep it to myself. :-)

**Comment by vincentb1** [comment]
cc @sreynal

Dear @RBornat, I would really appreciate if you published the fixes. I am maintaining [jPicEdt](http://www.jpicedt.org/), and I am trying to make a MACOS bundle for it with JarBundler, and when I do this the bundle requires old 1.6 java run time, while jPicEdt can run on more recent runtimes.

**Comment by slajar** [comment]
@RBornat I agree with @vincentb1 . Could you please create a PR so we can publish it?

**Comment by RBornat** [comment]
Will do. 

Richard

**Comment by RBornat** [comment]
I'm afraid you are going to hold my hand on this. I have never made a pull request. 

What I have is:

1. a cloned copy of JarBundler repo from github

2. a modified copy of that repo, inside the RBornat/jape repository in the distrib/MacOSX folder (pushed to github)

3. a modified copy of ultramixer's universaljavaapplicationstub, also inside the RBornat/jape repo, pushed to github

2 and 3 together work in modern MacOSs -- High Sierra onwards for sure, and they even seem to work in Big Sur (3 removes a lot of hoo-hah about sorting the various java machinery, because it didn't work and java_home does it better; it ignores stuff about maximum version of java).

So: what do I have to do to make a pull request? Should I make a fork in my local jarbundler repo and start from that? The info I can see seems to be what to do if there's a fork in ultramixer's repo.

You can see that I'm confused.

Richard

**Comment by slajar** [comment]
@RBornat  sure, please provide a pullrequest to discuss here.

**Comment by vincentb1** [comment]
This link explains how to create a Pull Request on GitHub :
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by tofi86** [comment]
This has been fixed with latest development on `master`.
