### ISSUE TITLE
version number mismatch

### ISSUE THREAD

**Issue by tofi86** [UltraMixer/JarBundler#2]
The maven version number in `pom.xml` (3.2.2) and the ant build version number in `build.xml` (2.3.2) deferr.

I assume they should be matching, right?

**Comment by tobium** [comment]
I would like to remove the ant build or is there any reason to keep the ant way?

**Comment by tofi86** [comment]
you're right. now that this is a maven project, we can use the `pom.xml` to build the distribution zip files...
Go ahead and remove the ant build file...

**Comment by tofi86** [comment]
now that these issues are resolved, please have a look at my PullRequests and consider a push to the maven central repository as version 3.3.0

Cheers :cocktail: 
Tobias

**Comment by tofi86** [comment]
> consider a push to the maven central repository as version 3.3.0

only looked into `jarbundler-core` package and saw that it is still at 3.2.2 while `jarbundler-parent` is at 3.3.0

**Comment by tobium** [comment]
fixed.
