### ISSUE TITLE
Missing definition

### ISSUE THREAD

**Issue by fstltna** [UltraMixer/JarBundler#9]
It is not finding the class loader. I get this:

```
Marisas-Mini:ThudNG-1.0 fstltna$ ant
Buildfile: /Users/fstltna/Documents/ThudNG2/ThudNG2/ThudNG-1.0/build.xml

BUILD FAILED
/Users/fstltna/Documents/ThudNG2/ThudNG2/ThudNG-1.0/build.xml:19: taskdef class net.sourceforge.jarbundler.JarBundler cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds

```

Please help!

**Comment by albertus82** [comment]
@fstltna the package name has changed, now you must use: `classname="com.ultramixer.jarbundler.JarBundler"`.

**Comment by fstltna** [comment]
Great, its now building the .app! But the icon is not showing, its using the generic app icon. Is there some setting i am missing?

Marisa

---

Newton City: https://NewtonCity.org
Opensim City: https://OpensimCity.org
Opensim Radio: http://radio.opensimcity.org:8188
Empire Directory: https://EmpireDirectory.net
Text Games List: https://empiredirectory.net/toplist/
Lugdunon City: https://LugdunonCity.org
Shorten.XYZ Traffic Exchange: http://Shorten.XYZ
Pocketfiction: https://Pocketfiction.com
Patreon Campaign: https://www.patreon.com/fstltna
IndieDB: http://www.indiedb.com/company/pocketfiction-pocketgames4me
LinkedIn: http://www.linkedin.com/in/marisagiancarla

**Comment by albertus82** [comment]
@fstltna Probably you have an invalid `icon` attribute value in the `jarbundler` element (Ant). Check that path, and verify that the bundle contains the icns file; you should find it in `Contents/Resources/` folder. Inspect also the `Info.plist` file: it should contain `<key>CFBundleIconFile</key>` followed by `<string>your-icon-file.icns</string>`.

**Comment by fstltna** [comment]
Ah, thats it. The old docs said it should be a png file. When i switched to my icns file its working fine. thanks for the help!

Marisa

---

Newton City: https://NewtonCity.org
Opensim City: https://OpensimCity.org
Opensim Radio: http://radio.opensimcity.org:8188
Empire Directory: https://EmpireDirectory.net
Text Games List: https://empiredirectory.net/toplist/
Lugdunon City: https://LugdunonCity.org
Shorten.XYZ Traffic Exchange: http://Shorten.XYZ
Pocketfiction: https://Pocketfiction.com
Patreon Campaign: https://www.patreon.com/fstltna
IndieDB: http://www.indiedb.com/company/pocketfiction-pocketgames4me
LinkedIn: http://www.linkedin.com/in/marisagiancarla

**Comment by fstltna** [comment]
Hey, I'm able to make the app now, but. In the generated file the fonts are messed up. I need a fixed-size font but it doesn't seem to be using it. Even if i change them after launching it. Any ideas?

Marisa

---

Newton City: https://NewtonCity.org
Opensim City: https://OpensimCity.org
Opensim Radio: http://radio.opensimcity.org:8188
Empire Directory: https://EmpireDirectory.net
Text Games List: https://empiredirectory.net/toplist/
Lugdunon City: https://LugdunonCity.org
Shorten.XYZ Traffic Exchange: http://Shorten.XYZ
Pocketfiction: https://Pocketfiction.com
Patreon Campaign: https://www.patreon.com/fstltna
IndieDB: http://www.indiedb.com/company/pocketfiction-pocketgames4me
LinkedIn: http://www.linkedin.com/in/marisagiancarla

**Comment by albertus82** [comment]
Can you upload a screenshot please?

**Comment by fstltna** [comment]
Here:
![screen shot 2016-10-10 at 9 45 55 pm](https://cloud.githubusercontent.com/assets/883076/19259088/2510bc7c-8f33-11e6-877b-c0175a6f4f27.png)

**Comment by albertus82** [comment]
I'm sorry but it seems to be a UI (Swing?) related question. Unfortunately I'm not using Swing, so I can't help you. IMHO this issue can be closed.

**Comment by slajar** [comment]
@fstltna looks like the classpath or any other search path for your font's are not correct. In case you think this is a JarBundler Problem, please open another Issue.
